import Head from 'next/head';
import { GraphQLClient, gql } from 'graphql-request';

import BlogCard from '@/components/BlogCard';

const graphcms = new GraphQLClient(
  'https://api-sa-east-1.hygraph.com/v2/cld6rdc1n21tw01t2f9qa1stf/master'
);

const QUERY = gql`
  {
    posts {
      id
      title
      slug
      datePublished
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      image {
        url
      }
    }
  }
`;

interface IPostProps {
  id: string;
  title: string;
  slug: string;
  datePublished: Date;
  content: {
    html: HTMLElement;
  };
  author: {
    name: string;
    avatar: {
      url: string;
    };
  };
  image: {
    url: string;
  };
}

interface IHomeProps {
  posts: IPostProps[];
}

export default function Blog({ posts }: IHomeProps) {
  return (
    <>
      <Head>
        <title>Blog | Fourstech Agência Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-20">
        {posts.map((item) => (
          <BlogCard
            id={item.id}
            title={item.title}
            slug={item.slug}
            author={item.author}
            image={item.image}
            datePublished={item.datePublished}
            key={item.id}
          />
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}
